CREATE TABLE `match` (
	`key` text PRIMARY KEY NOT NULL,
	`event_key` text NOT NULL,
	`comp_level` text NOT NULL,
	`match_number` integer NOT NULL,
	`set_number` integer NOT NULL,
	`red_alliance_id` integer NOT NULL,
	`blue_alliance_id` integer NOT NULL,
	`red_score_id` integer NOT NULL,
	`blue_score_id` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `match_alliance` (
	`id` integer PRIMARY KEY NOT NULL,
	`station1` integer,
	`station2` integer,
	`station3` integer
);
--> statement-breakpoint
CREATE TABLE `match_alliance_score` (
	`id` integer PRIMARY KEY NOT NULL,
	`auto_line_robot_1` integer,
	`auto_line_robot_2` integer,
	`auto_line_robot_3` integer,
	`auto_amp_note_count` integer,
	`auto_amp_note_points` integer,
	`auto_leave_points` integer,
	`auto_points` integer,
	`auto_speaker_note_count` integer,
	`auto_speaker_note_points` integer,
	`auto_total_note_points` integer,
	`coop_note_played` integer,
	`coop_bonus_achieved` integer,
	`coop_criteria_met` integer,
	`end_game_harmony_points` integer,
	`end_game_note_in_trap_points` integer,
	`end_game_on_stage_points` integer,
	`end_game_park_points` integer,
	`end_game_robot_1` text,
	`end_game_spot_light_bonus_points` integer,
	`end_game_total_stage_points` integer,
	`ensamble_bonus_achieved` integer,
	`ensamble_bonus_on_stage_robots_threshold` integer,
	`ensamble_bonus_stage_points_threshold` integer,
	`foul_count` integer,
	`foul_points` integer,
	`g206_penalty` integer,
	`g408_penalty` integer,
	`g424_penalty` integer,
	`melody_bonus_achieved` integer,
	`melody_bonus_threshold` integer,
	`melody_bonus_threshold_coop` integer,
	`melody_bonus_threshold_non_coop` integer,
	`mic_center_stage` integer,
	`mic_stage_left` integer,
	`mic_stage_right` integer,
	`rp` integer,
	`tech_foul_count` integer,
	`teleop_amp_note_count` integer,
	`teleop_amp_note_points` integer,
	`teleop_points` integer,
	`teleop_speaker_note_amplified_count` integer,
	`teleop_speaker_note_amplified_points` integer,
	`teleop_speaker_note_count` integer,
	`teleop_speaker_note_points` integer,
	`teleop_total_note_points` integer,
	`total_points` integer,
	`trap_center_stage` integer,
	`trap_stage_left` integer,
	`trap_stage_right` integer
);
